book table page
BeetrootAcademyAccount2/group3-html-css pull request #8
Opened 2024-03-12 18:32 UTC by platiins

adding a book-table page to our website :) 
form inputs have enabled validation and red borders when invalid, the same way as on **the job application page**, to keep up style consistency

2024-03-12 18:51 UTC, annie-uchiha approved these changes

2024-03-13 09:07 UTC, valenkir requested changes
The form look good, but I've found a couple of things that need to be added:
1. could you please add a link to your form to the "Book a table" button on the home page?
2. according to the design, the fields of the form should have a border of 1px and #D2D2D2 color. if you omitted this style intentionally, then let it be :)
3. I was googling how to make a button act like a link and in all the resources they put the button tag inside the a tag, not vice versa. I'm not sure if it is indeed the best practice, but maybe we should consider doing the same (with the "Order now" and "Book a table" buttons). example: https://www.freecodecamp.org/news/how-to-create-an-html-button-that-acts-like-a-link/

2024-03-14 07:37 UTC, platiins commented
@valenkir thank you for your feedback!

i have successfully merged your changes _(responsive nav)_ to my branch and resolved appeared conflicts. i also have added borders to the inputs, have not noticed that style before, because it looks like inherited from a browser ;D 

regarding adding links to buttons - the material you have sent is very useful, thanks! i used the syntax provided there, so now my book-table page is linked to all other pages by wrapping the 'order now' `<button>` in a `<a>` tag, the same as the 'book table' button

2024-03-15 14:38 UTC, valenkir approved these changes

2024-03-15 14:40 UTC, merged